### ISSUE TITLE
Converting WAFS to server-side rendering

### ISSUE THREAD

**Issue by standrd** [RowinRuizendaal/progressive-web-apps-2021#3]
## General feedback regarding assignment

* :heavy_check_mark: **Website is deployed server side on Heroku, and is functioning**
* :heavy_check_mark: **Used Express router to split routes, you understand how Express works**
* :warning: **Could look into some more tooling**

### Some things I think can be easily resolved

* I would recommend sticking to English variable names if the rest is all English:
https://github.com/RowinRuizendaal/progressive-web-apps-2021/blob/19266bfd26ad43722f9255ea7d028cc73d67e7c7/routes/src/index.js#L93-L94

* If you want to write more ES6 code, it might be worth looking into something like Babel to be able to convert this to 'import' and 'export':
https://github.com/RowinRuizendaal/progressive-web-apps-2021/blob/19266bfd26ad43722f9255ea7d028cc73d67e7c7/routes/src/index.js#L1-L3

* You're mixing async await & promise.then here, you only need to use one of them. Since it's already an async function, you can just use the await:
https://github.com/RowinRuizendaal/progressive-web-apps-2021/blob/19266bfd26ad43722f9255ea7d028cc73d67e7c7/routes/src/index.js#L33-L38

I've seen this multiple times in your code, you're doing double syntax which is unnecessary.

* I think it would be more neat to do the require/import at the top here:
`app.use(require('./routes/router'));`

**Comment by RowinRuizendaal** [comment]
Thanks for the feedback @StanBankras, I agree with you, I will fix this asap :)
