### ISSUE TITLE
Code review week 1

### ISSUE THREAD

**Issue by RobinFrugte97** [RowinRuizendaal/progressive-web-apps-2021#4]
Yo Rowin!

Goed dat je hebt gedacht aan deployen, alleen gooit ie een error. Even naar kijken misschien ;)

Wat je readme betreft, ik denk dat je heel veel kan gebruiken uit je WAFS readme, maar niet alles. Kijk wat relevant is. Dingen die je kan toevoegen zijn: Een stukje over je packages. Welke packages gebruik je en waarom? Beschrijf dit en een linkje naar de npm docs zou niet misstaan. Hetzelfde geldt voor je scripts. Momenteel heb je er twee die redelijk voor zichzelf spreken, maar als je er meer aan toevoegt, is het handig om even te omschrijven wat voor keuzes je hebt gemaakt en hoe je script chain in elkaar steekt.

Goed dat je je routes hebt gescheiden, alleen zou ik ze even in een variable zetten, zo hou je je requires gescheiden van de rest van je code en het wordt wat duidelijker.

Je templates zijn netjes gescheiden, goed bezig!

Kijk nog even naar wat meer tooling. Als je geen idee hebt, kijk even bij je teamgenoten en zoek op wat ze gebruiken.

Succes!

**Comment by RowinRuizendaal** [comment]
Hey Robin,

Bedankt voor je feedback, ik was er inderdaad mee bezig vandaar dat die een error gaf haha inmiddels heb ik dat opgelost. :)
